### PR TITLE
bump to lerc (and leaflet) 1.x

### PR DESCRIPTION
**Pull request by jgravois**

### CODE REVIEW

**Comment by lucianpls** [comment]
Demo is broken, at least in firefox.

**Comment by jgravois** [comment]
thanks for reporting @lucianpls. 

 tested in `v47` of firefox (and `v50.1.0`) on my mac and everything looked fine. what version are you using? what OS?

**Comment by lucianpls** [comment]
Windows, Firefox 50.1.  It looks like this

image

**Comment by jgravois** [comment]
@lucianpls and i sat down to debug and the problem is only reproducible on one machine.

for some reason, even though all the appropriate tiles are being fetched and decoded, duplicates are drawn on the screen (until the slider is moved) and very few of the `xmlHttpRequest` callbacks are being fired.

we tried modifying his browser settings and disabling extensions, but so far we've found no joy.

**Pull request merged**
